#ifndef _INJECTOR_
#define _INJECTOR_

#include "syscall.h"

typedef enum _INJECTOR_ERROR {
	INJECTOR_NO_ERROR,
	INJECTOR_OPEN_FILE_ERROR,
	INJECTOR_PE_PARSE_ERROR,
	INJECTOR_PE_LOAD_ERROR,
	INJECTOR_HANDLER_ENTRY_NOT_FOUND,
	INJECTOR_INKERNEL_ERROR,
	INJECTOR_NOT_A_DLL_ERROR
	} INJECTOR_ERROR;

INJECTOR_ERROR
InjectDllFile(
	IN char *FileName,
	IN EVENT EventId
);

#endif
