/*
 * SetupFrame.java
 *
 * Created on 2007年8月8日, 下午4:44
 */

package Explorer;

import FtpProcess.FtpClientProxy;
import Explorer.SiteProperty;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author  Administrator
 */
public class SetupFrame extends javax.swing.JFrame {
    
	private static final long serialVersionUID = 2345968529580114839L;
	
	private class SiteListModel implements ListModel {
	
	private Vector<Vector<String>> info;
	
	private ArrayList<ListDataListener> listeners=new ArrayList<ListDataListener>();
	
	public SiteListModel() {
	    info=new Vector<Vector<String>>();
	    Vector<FtpClientProxy> sites=ExplorerConfig.getInst().sites;
	    for (int i=0;i<sites.size();i++)
		info.add(sites.elementAt(i).infoOut());
	}
	
	public int getSize() {
	    return info.size();
	}
	
	public Object getElementAt(int index) {
	    return info.elementAt(index).elementAt(0);
	}
	
	public Vector<String> getInfo(int index) {
	    return info.elementAt(index);
	}
	
	public void addListDataListener(ListDataListener l) {
	    listeners.add(l);
	}
	
	public void removeListDataListener(ListDataListener l) {
	    listeners.remove(l);
	}
	
	public void delete(int index) {
	    info.remove(index);
	    for (int i=listeners.size()-1;i>=0;i--)
		listeners.get(i).intervalRemoved(new ListDataEvent(this,ListDataEvent.INTERVAL_REMOVED,index,index));
	}
	
	public void edit(int index,Vector<String> data) {
	    info.set(index,data);
	    for (int i=listeners.size()-1;i>=0;i--)
		listeners.get(i).intervalAdded(new ListDataEvent(this,ListDataEvent.CONTENTS_CHANGED,index,index));
	}
	
	public void add(int index,Vector<String> data) {
	    info.add(index+1,data);
	    for (int i=listeners.size()-1;i>=0;i--)
		listeners.get(i).intervalAdded(new ListDataEvent(this,ListDataEvent.INTERVAL_ADDED,index+1,index+1));
	}
	
	private void updateInfo() {
	    UltraExplorer.treeViewWindow.killNetwork();
	    ExplorerConfig.getInst().sites.clear();
	    for (int i=0;i<info.size();i++)
		ExplorerConfig.getInst().sites.add(
		    new FtpClientProxy(
		    info.elementAt(i).elementAt(1),
		    new Integer(info.elementAt(i).elementAt(2)),
		    info.elementAt(i).elementAt(3),
		    info.elementAt(i).elementAt(4),
		    info.elementAt(i).elementAt(0)
		    )
		);
	    UltraExplorer.treeViewWindow.generateNetwork();
	}
	
    }
    
    /** Creates new form SetupFrame */
    public SetupFrame() {
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lport = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        serverTimeOut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clientTimeOut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        siteList = new javax.swing.JList();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        change = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setTitle("\u7f51\u7edc\u8bbe\u7f6e");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lport.setText("FTP\u670d\u52a1\u5668\u7aef\u53e3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lport, gridBagConstraints);

        port.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(port, gridBagConstraints);

        jLabel2.setText("FTP\u670d\u52a1\u5668\u8d85\u65f6\u65f6\u95f4(\u6beb\u79d2):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        serverTimeOut.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(serverTimeOut, gridBagConstraints);

        jTabbedPane1.addTab("FTP\u670d\u52a1\u5668\u8bbe\u7f6e", jPanel1);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("FTP\u5ba2\u6237\u7aef\u8d85\u65f6\u65f6\u95f4(\u6beb\u79d2):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel3, gridBagConstraints);

        clientTimeOut.setMinimumSize(new java.awt.Dimension(100, 21));
        clientTimeOut.setPreferredSize(new java.awt.Dimension(100, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(clientTimeOut, gridBagConstraints);

        jLabel4.setText("\u6536\u85cf\u7684FTP\u7ad9\u70b9:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel4, gridBagConstraints);

        siteList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(siteList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        add.setText("\u6dfb\u52a0");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(add, gridBagConstraints);

        delete.setText("\u5220\u9664");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(delete, gridBagConstraints);

        change.setText("\u4fee\u6539");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(change, gridBagConstraints);

        jTabbedPane1.addTab("FTP\u5ba2\u6237\u7aef\u8bbe\u7f6e", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        ok.setText("\u786e\u5b9a");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jPanel3.add(ok);

        cancel.setText("\u53d6\u6d88");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel3.add(cancel);
        cancel.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	port.setText(((Integer)ExplorerConfig.getInst().get(ExplorerConfig.SERVERPORT)).toString());
	serverTimeOut.setText(((Integer)ExplorerConfig.getInst().get(ExplorerConfig.SERVERTIMEOUT)).toString());
	clientTimeOut.setText(((Integer)ExplorerConfig.getInst().get(ExplorerConfig.CLIENTTIMEOUT)).toString());
	siteList.setModel(new SiteListModel());
    }//GEN-LAST:event_formComponentShown

    @SuppressWarnings("unchecked")
	private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
	if (siteList.getSelectionModel().isSelectionEmpty()) return;
	int index=siteList.getSelectedIndex();
	Vector<String> info=(Vector) ((SiteListModel)siteList.getModel()).getInfo(index).clone();
	new SiteProperty(this,info).setVisible(true);
	if (info.size()==5)
	    ((SiteListModel)siteList.getModel()).edit(index,info);
    }//GEN-LAST:event_changeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
	if (siteList.getSelectionModel().isSelectionEmpty()) return;
	((SiteListModel)siteList.getModel()).delete(siteList.getSelectedIndex());
    }//GEN-LAST:event_deleteActionPerformed
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
	int index;
	if (siteList.getSelectionModel().isSelectionEmpty())
	    index=siteList.getModel().getSize()-1;
	else
	    index=siteList.getSelectedIndex();
	Vector<String> info=new Vector<String>();
	new SiteProperty(this,info).setVisible(true);
	if (info.size()==5)
	    ((SiteListModel)siteList.getModel()).add(index,info);
    }//GEN-LAST:event_addActionPerformed
    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
	try {
	    int i=new Integer(port.getText());
	    if (i<=0||i>=65536) throw new Exception();
	    i=new Integer(serverTimeOut.getText());
	    i=new Integer(clientTimeOut.getText());
	}catch(Exception e){
	    JOptionPane.showMessageDialog(this,"请确认输入数据的正确性！",this.getTitle(),JOptionPane.WARNING_MESSAGE);
	    return;
	}
	ExplorerConfig.getInst().serverPort=new Integer(port.getText());
	ExplorerConfig.getInst().serverTimeOut=new Integer(serverTimeOut.getText());
	ExplorerConfig.getInst().clientTimeOut=new Integer(clientTimeOut.getText());
	UltraExplorer.startFTPServer();
	((SiteListModel)siteList.getModel()).updateInfo();
	this.setVisible(false);
    }//GEN-LAST:event_okActionPerformed
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
	this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    // 变量声明 - 不进行修改//GEN-BEGIN:variables
    javax.swing.JButton add;
    javax.swing.JButton cancel;
    javax.swing.JButton change;
    javax.swing.JTextField clientTimeOut;
    javax.swing.JButton delete;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JLabel lport;
    javax.swing.JButton ok;
    javax.swing.JTextField port;
    javax.swing.JTextField serverTimeOut;
    javax.swing.JList siteList;
    // 变量声明结束//GEN-END:variables
    
}
