#ifndef _COFF_
#define _COFF_

typedef struct _COFF_HEADER {
	USHORT Machine;
	USHORT NumberOfSections;
	ULONG TimeDateStamp;
	ULONG PointerToSymbolTable;
	ULONG NumberOfSymbols;
	USHORT SizeOfOptionalHeader;
	USHORT Characteristics;
} COFF_HEADER, *PCOFF_HEADER;


#define IMAGE_FILE_MACHINE_UNKNOW	0x0
//#define IMAGE_FILE_MACHINE_AM33		0x1d3
#define IMAGE_FILE_MACHINE_AMD64		0x8664
//#define IMAGE_FILE_MACHINE_ARM		0x1c0
//#define IMAGE_FILE_MACHINE_EBC		0xebc
//#define IMAGE_FILE_MACHINE_I386		0x14c
//#define IMAGE_FILE_MACHINE_IA64		0x200
#define IMAGE_FILE_MACHINE_M32R		0x9041
//#define IMAGE_FILE_MACHINE_MIPS16		0x266
//#define IMAGE_FILE_MACHINE_MIPSFPU		0x366
//#define IMAGE_FILE_MACHINE_MIPSFPU16	0x466
//#define IMAGE_FILE_MACHINE_POWERPC	0x1f0
//#define IMAGE_FILE_MACHINE_POWERPCFP	0x1f1
//#define IMAGE_FILE_MACHINE_R4000		0x166
//#define IMAGE_FILE_MACHINE_SH3		0x1a2
//#define IMAGE_FILE_MACHINE_SH3DSP	0x1a3
//#define IMAGE_FILE_MACHINE_SH4		0x1a6
//#define IMAGE_FILE_MACHINE_SH5		0x1a8
//#define IMAGE_FILE_MACHINE_THUMB		0x1c2
//#define IMAGE_FILE_MACHINE_WCEMIPSV2	0x169


#define IMAGE_FILE_RELOCS_STRIPPED			0x0001
#define IMAGE_FILE_EXECUTABLE_IMAGE			0x0002
#define IMAGE_FILE_LINE_NUMS_STRIPPED		0x0004
#define IMAGE_FILE_LOCAL_SYMS_STRIPPED		0x0008
#define IMAGE_FILE_AGGRESSIVE_WS_TRIM		0x0010
#define IMAGE_FILE_LARGE_ADDRESS_AWARE		0x0020
#define IMAGE_FILE_BYTES_REVERSED_LO			0x0080
#define IMAGE_FILE_32BIT_MACHINE				0x0100
#define IMAGE_FILE_DEBUG_STRIPPED				0x0200
#define IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP	0x0400
#define IMAGE_FILE_NET_RUN_FROM_SWAP		0x0800
#define IMAGE_FILE_SYSTEM						0x1000
#define IMAGE_FILE_DLL							0x2000
#define IMAGE_FILE_UP_SYSTEM_ONLY				0x4000
#define IMAGE_FILE_BYTES_REVERSED_HI			0x8000

#endif
