#ifndef _RELOC_
#define _RELOC_

typedef struct _RELOCATION_BLOCK_HEADER {
	ULONG PageRVA;
	ULONG BlockSize;
} RELOCATION_BLOCK_HEADER, *PRELOCATION_BLOCK_HEADER;

typedef struct _RELOCATION_BLOCK_ENTRY {
	unsigned Offset:12;
	unsigned Type:4;
} RELOCATION_BLOCK_ENTRY, *PRELOCATION_BLOCK_ENTRY;

typedef struct _RELOCATION_BLOCK {
	RELOCATION_BLOCK_HEADER Header;
	RELOCATION_BLOCK_ENTRY Entries;
} RELOCATION_BLOCK, *PRELOCATION_BLOCK;

#endif
